runtime: custom
env: flex
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 10
resources:
  cpu: 2
  memory_gb: 2
  disk_size_gb: 10
handlers:
  - url: /.*
    script: auto
    secure: always
    redirect_http_response_code: 301